### ISSUE TITLE
Use cosmos db as mongo db 

### ISSUE THREAD

**Issue by warrenzhu25** [VSChina/PiggyMetrics#2]
Just need to change:
```
spring:
  data:
    mongodb:
      database: databaseName
      uri: connection string copied from portal
```
